import seaborn as sns
import pandas as pd 
import matplotlib.pyplot as plt 
dataframe = sns.load_dataset("titanic")
print(dataframe)

#contar pasajeros por clase
sns.countplot(x="pclass", data=dataframe)
plt.title("contar pasajeros por clases")
plt.xlabel("Clases")
plt.ylabel("Cantidad de personas")
plt.savefig("conteo de pasajeros por clase")
plt.show()
print("------------")
print("------------")
#Superviviencia por sexo
sns.barplot(x="sex", y="survived", data=dataframe)
plt.title("Tasa supervivencia por sexo")
plt.xlabel("Clases")
plt.ylabel("proporcion de personas")
plt.savefig("supervivencia por sexo")
plt.show()
print("------------")
print("------------")
#boxplot
plt.figure()
sns.boxplot(x="pclass", y="age", data=dataframe)
plt.title("distribucionm de edad por clase")
plt.savefig("img 3 - distribucion de edad por clase")
plt.show()
print("------------")
print("------------")
#distribucion
plt.figure()
sns.scatterplot(x="age", y="fare", hue="sex", data=dataframe)
plt.title("Relacion entre edad y tarifa")
plt.savefig("img 4 - relacion entre edad y tarifa")
plt.show()
print("------------")
print("------------")
#mapa correlaciones de calor
plt.figure()
corr=dataframe.select_dtypes(include=["number"]).corr()
sns.heatmap(corr, annot=True, cmap="coolwarm")
plt.title("mapa de correlaciones")
plt.savefig("img 5 - mapa de correlaciones")
plt.show()
print("------------")
print("------------")
#pairplot para varias variables
plt.figure()
sns.pairplot(dataframe[["age", "fare", "survived","pclass"]], hue="survived")
plt.title("pairplot para varias variables")
plt.savefig("img 6 - pairplot para varias variables")
plt.show()
print("------------")
print("------------")
#violin plot por sexo
plt.figure()
sns.violinplot(x="sex", y="age", data=dataframe)
plt.title("violinplo(...)-> none")
plt.savefig("img 7 - violinplo por sexo")
plt.show()
print("------------")
print("------------")
#histograma de edad
plt.figure()
sns.histplot(dataframe["age"].dropna(), bins=20, kde=True)
plt.title("histograma por edad")
plt.savefig("img 8- histograma por edad")
plt.show()