import pandas as pd
titanic = pd.read_csv("C:\\Users\\HP\\Desktop\\PYTHON\\Ambox\\Unidad 4\\titanic.csv")
mujeres_por_clase=titanic[titanic["Sex"]=="female"]["Pclass"].value_counts()
print(mujeres_por_clase)
print("--------------")
print("--------------")
import matplotlib.pyplot as plt 
tarifas_3ra=titanic[titanic["Pclass"]==3]["Fare"]
print(tarifas_3ra.describe())
plt.hist(tarifas_3ra, bins=30, edgecolor="black")
plt.title("Distribucion de tarifas 3ra clase")
plt.xlabel("Tarifa")
plt.ylabel("Cantidad de pasajeros")
plt.savefig("Distribucion de tarifas 3ra clase")
plt.show()
print("--------------")
print("--------------")
edad_promedio_por_puerto=titanic.groupby("Embarked")["Age"].mean()
print(edad_promedio_por_puerto)
print("--------------")
print("--------------")
supervivencia_por_sexo=titanic.groupby(["Sex", "Survived"]).size().unstack()
print(supervivencia_por_sexo)
supervivencia_por_sexo.plot(kind="bar", stacked=True)
plt.title("Supervivencia y no supervivientes por sexo")
plt.xlabel("Sexo")
plt.ylabel("Cantidad de personas")
plt.legend(["No sobrevivio", "Sobrevivio"])
plt.savefig("Supervivientes y no supervivientes por sexo")
plt.show()
